### ISSUE TITLE
The device's problem. 

### ISSUE THREAD

**Issue by CHGSM** [praveen-palanisamy/macad-gym#19]
Hello. Can these project run on the computer without GPU? When I try to run it on CPU, it doesn't work. Looking for your apply. Thank you！

**Comment by praveen-palanisamy** [comment]
Hi @CHGSM , 
Unfortunately, the [Unreal Engine 4](https://www.unrealengine.com/en-US/) runtime used by the CARLA simulator which powers [MACAD-Gym](https://github.com/praveen-palanisamy/macad-gym) depends on a GPU. It's not feasible to run these environments on CPU only machine. 

That said, you can use a [Google Colab](https://colab.research.google.com) instance to get a free access to a shared GPU machine for running MACAD-Gym
