### ISSUE TITLE
Cannot run Agent interface demo code

### ISSUE THREAD

**Issue by mengyuest** [praveen-palanisamy/macad-gym#30]
Hi, I was not able to run your demo code under the ["Agent interface"](https://github.com/praveen-palanisamy/macad-gym#agent-interface) section in your README. I tried CARLA 0.9.4, 0.9.5 and 0.9.9.4 and all failed. I was using Ubuntu18.04 with one RTX2080Ti GPU. The python version is 3.6.12. I installed the MACAD-Gym via Option1

When I tried CARLA 0.9.4, the CARLA window would quickly show up and disappeared, and the error was: 
```
Running simulation in single-GPU mode
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.5 
WARNING: Simulator API version  = 0.9.4 
Error during reset: Traceback (most recent call last):
  File "/home/meng/miniconda3/envs/macad/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 581, in reset
    self._init_server()
  File "/home/meng/miniconda3/envs/macad/lib/python3.6/site-packages/macad_gym/carla/multi_env.py", line 511, in _init_server
    carla.Rotation(yaw=180 + angle, pitch=-15)))
RuntimeError: trying to access an expired episode; a new episode was started in the simulation but an object tried accessing the old one.
```

Then I tried CARLA 0.9.5, but the CARLA window would stuck at the initial scene and not responding.

At last I tried CARLA 0.9.9.4, and it continued saying `Could not connect to Carla server because: rpc::rpc_error during call in function version` and finally ended with:
```
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
Malloc Size=65535 LargeMemoryPoolOffset=131119 
terminating with uncaught exception of type std::__1::bad_weak_ptr: bad_weak_ptr
Signal 6 caught.
Malloc Size=124960 LargeMemoryPoolOffset=256096 
Segmentation fault (core dumped)
```

I am able to run each CARLA simulator alone, but I just cannot make it via the `gym` interface. Do you know what could be the reason for this? Thanks.

**Comment by mengyuest** [comment]
Okay I am able to run for CARLA 0.9.4 with macad-gym installed via Option2, though I am still curious about the problem in Option1

**Comment by YuffieHuang** [comment]
> Okay I am able to run for CARLA 0.9.4 with macad-gym installed via Option2, though I am still curious about the problem in Option1

Thank you. I met the same issue and Option 2 did help.

**Comment by praveen-palanisamy** [comment]
Hi @mengyuest & @YuffieHuang ,
Sorry for the delayed response and thank you for reporting this issue.
The issue is related to the warning message that you got from the CARLA server, quoted below:
```bash
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.5 
WARNING: Simulator API version  = 0.9.4 
```
You seem to have CARLA client version `0.9.5` installed in your python environment while running with the CARLA server version `0.9.4`.

You can solve the issue by installing CARLA client version `0.9.4` using this command: `pip install carla==0.9.4`. 

With the correct version of the `carla` python client package, The simpler install `Option 1`: `pip install macad-gym` should work.

Please try it out and post if it does/doesn't solve the issue.

**Comment by praveen-palanisamy** [comment]
Assuming that this issue is resolved. Please re-open if you need help further.
