### ISSUE TITLE
Running sample code

### ISSUE THREAD

**Issue by b-safwat** [praveen-palanisamy/macad-gym#39]
Hi, 

I am trying to run the sample code: 
```
import gym
import macad_gym
env = gym.make("HomoNcomIndePOIntrxMASS3CTWN3-v0")
```

and I get the following error: 
```
free(): invalid pointer
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Carla is also running but I don't guess that is related at this point.

**Comment by praveen-palanisamy** [comment]
Hi @b-safwat ,

I am assuming you followed the [Getting started guide](https://github.com/praveen-palanisamy/macad-gym#getting-started) and set-up your environment?

Could you describe your environment (CARLA server, client versions, python version, MACAD-Gym version) if it's different from what's in the [README](https://github.com/praveen-palanisamy/macad-gym/blob/master/README.md)

Also, can you attach the full console log when you run the sample code?
