### ISSUE TITLE
How to visualize the learning environment?

### ISSUE THREAD

**Issue by qiangyuchuan** [praveen-palanisamy/macad-gym#66]
Hello there, I am new to this project. The work you have done is remarkable! Here is a question I encontered.

I can run the basic_agent.py in the examples folder, but when I add env.render() into the for loop, it occurs an NotImplementedError like below.

Traceback (most recent call last):
  File "/home/moda/macad-gym-master/examples/basic_agent.py", line 34, in <module>
    env.render()
  File "/home/moda/macad-gym-master/src/macad_gym/multi_actor_env.py", line 73, in render
    raise NotImplementedError
NotImplementedError
Killing live carla processes set()

Looking forward to seeing your reply!

**Comment by praveen-palanisamy** [comment]
Hi @qiangyuchuan ,

The observation (`obs`) returned by the `env.step(...)` is an image which you can directly visualize by using visualization tools like OpenCV's `cv2.imshow()` or Pillow (PIL)'s [ImageShow](https://pillow.readthedocs.io/en/stable/reference/ImageShow.html).

As an example, you could add:

```python
cv2.imshow("observation", obs)  # Requires import cv2
cv2.waitKey(0)  # Wait for a keypress
```
After this line:
https://github.com/praveen-palanisamy/macad-gym/blob/bf40a5363669fd302a972e95ee8531613f9d82e1/examples/basic_agent.py#L38

Hope that helps.

**Comment by qiangyuchuan** [comment]
Thanks a lot, it works.
