### ISSUE TITLE
The latest pull request is incomplete

### ISSUE THREAD

**Issue by Morphlng** [praveen-palanisamy/macad-gym#73]
## Description

I've just tested the latest PR and it seems like we didn't "merge them all".

For example, in the latest PR, the author `_decode_obs` before calling `multi_view_render`, the latter function used to handle the decoding process by itself.

https://github.com/praveen-palanisamy/macad-gym/blob/24907d8665ab993a3f6a3cfa0160aede0335282d/src/macad_gym/carla/multi_env.py#L1061-L1063

However, in the `multi_view_render` function, there still exist the decoding process, which causes problems.

https://github.com/praveen-palanisamy/macad-gym/blob/24907d8665ab993a3f6a3cfa0160aede0335282d/src/macad_gym/viz/render.py#L25-L29

The result can be seen below:

![wrong](https://user-images.githubusercontent.com/50166287/204121297-20b95b9c-407e-4bc7-8515-08880c5b4711.png)

## Solution

I went back and checked all the pull request started by @johnMinelli and found that in PR https://github.com/praveen-palanisamy/macad-gym/pull/68#issue-1424749788, he had removed the decoding process in `render.py`, but this PR hasn't merged yet.

Please do further testing and make sure all changes have been merged.

**Comment by johnMinelli** [comment]
Hi, you are totally right. A fast fix would be change that line in `render.py` to

``
surface = pygame.surfarray.make_surface(im)
``

Let's hear from @praveen-palanisamy on what to do

**Comment by praveen-palanisamy** [comment]
Hi @Morphlng , thank you for catching the bug with the latest PR merge and posting the details! 
It will be good to add tests to catch them automatically.
Let me review #68 to resolve this soon.

**Comment by praveen-palanisamy** [comment]
@Morphlng : This should be fixed now on the main branch. Many thanks for reporting it!
