### ISSUE TITLE
Implement of IMPALA Agent Examples

### ISSUE THREAD

**Issue by Kinvy66** [praveen-palanisamy/macad-gym#88]
In the experimental part of the macad-gym paper, you mentioned that using the IMPALA agent control vehicle in macad-gym, but I did not find this part of the realization in the latest code. Excuse me, whether this code is open source, or there are this part of the code in the historical version.

**Comment by praveen-palanisamy** [comment]
Hi @Kinvy66 ,
Please see the [MACAD-Agents repository](https://github.com/praveen-palanisamy/macad-agents) for the IMPALA agent and other multi-agent algorithm implementation that can be trained to control vehilces using MACAD-Gym. The README include [instructions on how to run/train/test MACAD-Agents](https://github.com/praveen-palanisamy/macad-agents#how-to-traintest-macad-agents) including the IMPALA Agent.

**Comment by Kinvy66** [comment]
Thanks!
